import ArrowUp from "@/public/upArrow.svg";
import ArrowDown from "@/public/downArrow.svg";
import ArrowRight from "@/public/rightArrow.svg";
import ArrowLeft from "@/public/leftArrow.svg";
import ArrowDownBlack from "@/public/arrow_downward_FILL0_wght400_GRAD0_opsz24.svg";
import ArrowUpBlack from "@/public/arrow_upward_FILL0_wght400_GRAD0_opsz24.svg";
import ArrowLeftBlack from "@/public/arrow_back_FILL0_wght400_GRAD0_opsz24.svg";
import ArrowRightBlack from "@/public/arrow_forward_FILL0_wght400_GRAD0_opsz24.svg";
import Stop from "@/public/stop.svg";
import StopBlack from "@/public/stop_black.svg";
import Obstacle from "@/public/obstacle.svg";
import tarunImg from "@/public/tarun.jpg";
import bharatImg from "@/public/bharat.jpg";
import sumvitImg from "@/public/sumvit.jpg";
import flowwhite from "@/public/flow-white.svg";
import flowblack from "@/public/flow-black.svg";
import titleLogo from "@/public/titleLogo.png";

export const AU = () => ArrowUp;
export const AD = () => ArrowDown;
export const AR = () => ArrowRight;
export const AL = () => ArrowLeft;
export const AUB = () => ArrowUpBlack;
export const ADB = () => ArrowDownBlack;
export const ARB = () => ArrowRightBlack;
export const ALB = () => ArrowLeftBlack;
export const STOP = () => Stop;
export const STOPB = () => StopBlack;
export const OB = () => Obstacle;
export const tarun = () => tarunImg;
export const sumvit = () => sumvitImg;
export const bharat = () => bharatImg;
export const flowWhite = () => flowwhite;
export const flowBlack = () => flowblack;
export const title = () => titleLogo;
